### ISSUE TITLE
Pass by value

### ISSUE THREAD

**Issue by m1keall1son** [sitara-systems/sitara-http#1]
Three methods are passing the argument by value unnecessarily: 

`void makeStringSafe(std::string input);`
- breaks the functionality of `makeStringSafe` as the sting passed is not made safe, the orphaned local copy in the function body is. 
  Should be: `void makeStringSafe( std::string &input );`

`std::string JsonToString(const Json::Value value);`
- unnecessary copy of `Json::Value`
  Should be: `std::string JsonToString(const Json::Value& value);`

`std::string mapToString(const std::map<std::string, std::string> map);`
- unnecessary copy of `std::map`
  Should be: `std::string mapToString(const std::map<std::string, std::string>& map);`

**Comment by morphogencc** [comment]
Fixed! Thanks.
